[build]
  functions = "netlify/functions"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"  # :splat captures the wildcard path
  status = 200
[dev]
  autoLaunch = false
  publish = "public"
  framework = "#static"